### ISSUE TITLE
Compiled JS failing when ran with Bunjs

### ISSUE THREAD

**Issue by ronhombre** [KotlinCrypto/secure-random#8]
![image](https://github.com/KotlinCrypto/secure-random/assets/118486316/734866cb-5c2c-4624-ab10-b1be7c450aa6)

Reproduction Steps:
1. Run `gradle browserWebpack`
2. Copy files in `build/compileSync/js/main/productionExecutable/kotlin` into a NodeJS project.
3. Use the Kotlin/JS compiled files that use secure-random.
4. Run Bunjs (Fails here).

Note: Additionally, using the compiled Webpack also causes the same bug when running on NodeJS.

_Work around: Delete the first if-statement and leave whatever was in the else statement._

**Comment by 05nelsonm** [comment]
Wondering if this is a KotlinJS bug or not as a ByteArray should register as a UInt8Array

**Comment by ronhombre** [comment]
![image](https://github.com/KotlinCrypto/secure-random/assets/118486316/d2ea3adb-4d86-4f1e-ac77-6c74d52f7711)

It still breaks when run with _Bunjs_.

Removing the code below fixes it.
```javascript
if (_get_isNode__xss3j(Companion_getInstance())) {
  _get_crypto__fwud1y(Companion_getInstance()).randomFillSync(array);
} else {
  
}
```

Leaving just the code below allows it to run.
```javascript
var offset = 0;
while (offset < bytes.length) {
  var len = bytes.length > 65536 ? 65536 : bytes.length;
  _get_crypto__fwud1y(Companion_getInstance()).getRandomValues(array.subarray(offset, offset + len | 0));
  offset = offset + len | 0;
}
```

**Comment by 05nelsonm** [comment]
What version of `Node.js` is being utilized by *bunjs*

`randomFillSync` should accept a `TypedArray`, not just a `Uint8Array`.

Alternatively, you could try to see if the same error happens when using https://github.com/whyoleg/cryptography-kotlin/tree/main/cryptography-random

**Comment by 05nelsonm** [comment]
#14 is up with a published SNAPSHOT. Could you test it out to verify the fix?

1. Add the following to your root project's `repositories` block
    ```kotlin
    allprojects {
        repositories {
            // ...
            maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
        }
    }
    ```
2. Use version `org.kotlincrypto:secure-random:0.3.1-SNAPSHOT`

**Comment by 05nelsonm** [comment]
> @05nelsonm Confirmed. Thanks for the fix.
> 
> ![image](https://private-user-images.githubusercontent.com/118486316/314582824-7d6b0862-8167-4d91-bf2f-8b360edafd78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTI5NDYsIm5iZiI6MTcxMDk1MjY0NiwicGF0aCI6Ii8xMTg0ODYzMTYvMzE0NTgyODI0LTdkNmIwODYyLTgxNjctNGQ5MS1iZjJmLThiMzYwZWRhZmQ3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNjM3MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmQxM2UxMTE5NWM0ZDlhMWRiMzJlMjQ2ZDlkZGE1NGZkYjUyMTlkNmYwMTlmNjFjM2Q5Yjc5YmI1OWViNGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sGskp-lvcAkzVkKfc2jwrwf9iMRHVJoGOQ2ay2mNdYM)

Great, will merge the fix and get a release out in a moment
